// Date: 01/08/2012 10:22:05 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelPowerDoor extends ModelBase
{
  //fields
    ModelRenderer wall;
  
  public ModelPowerDoor()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      wall = new ModelRenderer(this, 0, 0);
      wall.addBox(0F, 8F, 0F, 2, 16, 16);
      wall.setRotationPoint(-1F, 0F, -8F);
      wall.setTextureSize(64, 32);
      wall.mirror = true;
      setRotation(wall, 0F, 0F, 0F);
  }
  
  public void renderModel(float f1)
{
    wall.render(f1);
}
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    wall.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
